//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_MKWII_WPF.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CT_MKWII_WPF.Resources.Languages.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Not Finished.
        /// </summary>
        public static string ButtonState_ConfigNotFinished {
            get {
                return ResourceManager.GetString("ButtonState_ConfigNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string ButtonState_Install {
            get {
                return ResourceManager.GetString("ButtonState_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Server.
        /// </summary>
        public static string ButtonState_NoServer {
            get {
                return ResourceManager.GetString("ButtonState_NoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string ButtonState_Play {
            get {
                return ResourceManager.GetString("ButtonState_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Offline.
        /// </summary>
        public static string ButtonState_PlayOffline {
            get {
                return ResourceManager.GetString("ButtonState_PlayOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonState_Update {
            get {
                return ResourceManager.GetString("ButtonState_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Sidebar_Button_Friends {
            get {
                return ResourceManager.GetString("Sidebar_Button_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Sidebar_Button_Home {
            get {
                return ResourceManager.GetString("Sidebar_Button_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My stuff.
        /// </summary>
        public static string Sidebar_Button_Mods {
            get {
                return ResourceManager.GetString("Sidebar_Button_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profiles.
        /// </summary>
        public static string Sidebar_Button_MyProfiles {
            get {
                return ResourceManager.GetString("Sidebar_Button_MyProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Sidebar_Button_Rooms {
            get {
                return ResourceManager.GetString("Sidebar_Button_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Sidebar_Button_Settings {
            get {
                return ResourceManager.GetString("Sidebar_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Sidebar_Category_General {
            get {
                return ResourceManager.GetString("Sidebar_Category_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Sidebar_Category_Online {
            get {
                return ResourceManager.GetString("Sidebar_Category_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Sidebar_Category_Other {
            get {
                return ResourceManager.GetString("Sidebar_Category_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string State_Installing {
            get {
                return ResourceManager.GetString("State_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string State_Loading {
            get {
                return ResourceManager.GetString("State_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string State_Updating {
            get {
                return ResourceManager.GetString("State_Updating", resourceCulture);
            }
        }
    }
}
