//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_MKWII_WPF.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CT_MKWII_WPF.Resources.Languages.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Action_Apply {
            get {
                return ResourceManager.GetString("Action_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Friend Code.
        /// </summary>
        public static string Action_CopyFriendCode {
            get {
                return ResourceManager.GetString("Action_CopyFriendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All.
        /// </summary>
        public static string Action_DisableAll {
            get {
                return ResourceManager.GetString("Action_DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All.
        /// </summary>
        public static string Action_EnableAll {
            get {
                return ResourceManager.GetString("Action_EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Action_Export {
            get {
                return ResourceManager.GetString("Action_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Action_Import {
            get {
                return ResourceManager.GetString("Action_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Action_Install {
            get {
                return ResourceManager.GetString("Action_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep.
        /// </summary>
        public static string Action_Keep {
            get {
                return ResourceManager.GetString("Action_Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe Later.
        /// </summary>
        public static string Action_MaybeLater {
            get {
                return ResourceManager.GetString("Action_MaybeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Action_No {
            get {
                return ResourceManager.GetString("Action_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Action_OK {
            get {
                return ResourceManager.GetString("Action_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string Action_OpenFolder {
            get {
                return ResourceManager.GetString("Action_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Action_Play {
            get {
                return ResourceManager.GetString("Action_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Offline.
        /// </summary>
        public static string Action_PlayOffline {
            get {
                return ResourceManager.GetString("Action_PlayOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Action_Rename {
            get {
                return ResourceManager.GetString("Action_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Action_Revert {
            get {
                return ResourceManager.GetString("Action_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Action_Yes {
            get {
                return ResourceManager.GetString("Action_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Attribute_Enabled {
            get {
                return ResourceManager.GetString("Attribute_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Attribute_Id {
            get {
                return ResourceManager.GetString("Attribute_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods Name.
        /// </summary>
        public static string Attribute_ModName {
            get {
                return ResourceManager.GetString("Attribute_ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Attribute_Name {
            get {
                return ResourceManager.GetString("Attribute_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Attribute_Title {
            get {
                return ResourceManager.GetString("Attribute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Attribute_Type {
            get {
                return ResourceManager.GetString("Attribute_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string PageTitle_Friends {
            get {
                return ResourceManager.GetString("PageTitle_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PageTitle_Home {
            get {
                return ResourceManager.GetString("PageTitle_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stuff.
        /// </summary>
        public static string PageTitle_Mods {
            get {
                return ResourceManager.GetString("PageTitle_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profiles.
        /// </summary>
        public static string PageTitle_MyProfiles {
            get {
                return ResourceManager.GetString("PageTitle_MyProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Details.
        /// </summary>
        public static string PageTitle_RoomDetails {
            get {
                return ResourceManager.GetString("PageTitle_RoomDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string PageTitle_Rooms {
            get {
                return ResourceManager.GetString("PageTitle_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PageTitle_Settings {
            get {
                return ResourceManager.GetString("PageTitle_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Not Finished.
        /// </summary>
        public static string State_ConfigNotFinished {
            get {
                return ResourceManager.GetString("State_ConfigNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting files....
        /// </summary>
        public static string State_Extracting {
            get {
                return ResourceManager.GetString("State_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string State_Installing {
            get {
                return ResourceManager.GetString("State_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string State_Loading {
            get {
                return ResourceManager.GetString("State_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Server.
        /// </summary>
        public static string State_NoServer {
            get {
                return ResourceManager.GetString("State_NoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string State_Updating {
            get {
                return ResourceManager.GetString("State_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Term_Error {
            get {
                return ResourceManager.GetString("Term_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Term_General {
            get {
                return ResourceManager.GetString("Term_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Term_No {
            get {
                return ResourceManager.GetString("Term_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Term_Offline {
            get {
                return ResourceManager.GetString("Term_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Term_Online {
            get {
                return ResourceManager.GetString("Term_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Term_Other {
            get {
                return ResourceManager.GetString("Term_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Term_Speed {
            get {
                return ResourceManager.GetString("Term_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Term_Success {
            get {
                return ResourceManager.GetString("Term_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Term_Unknown {
            get {
                return ResourceManager.GetString("Term_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Term_Warning {
            get {
                return ResourceManager.GetString("Term_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Term_Yes {
            get {
                return ResourceManager.GetString("Term_Yes", resourceCulture);
            }
        }
    }
}
