//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT_MKWII_WPF.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CT_MKWII_WPF.Resources.Languages.Lang.nl", typeof(Lang_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrienden.
        /// </summary>
        internal static string Sidebar_Button_Friends {
            get {
                return ResourceManager.GetString("Sidebar_Button_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startpagina.
        /// </summary>
        internal static string Sidebar_Button_Home {
            get {
                return ResourceManager.GetString("Sidebar_Button_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        internal static string Sidebar_Button_Mods {
            get {
                return ResourceManager.GetString("Sidebar_Button_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn profielen.
        /// </summary>
        internal static string Sidebar_Button_MyProfiles {
            get {
                return ResourceManager.GetString("Sidebar_Button_MyProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speel ruimtes.
        /// </summary>
        internal static string Sidebar_Button_Rooms {
            get {
                return ResourceManager.GetString("Sidebar_Button_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string Sidebar_Button_Settings {
            get {
                return ResourceManager.GetString("Sidebar_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemeen.
        /// </summary>
        internal static string Sidebar_Category_General {
            get {
                return ResourceManager.GetString("Sidebar_Category_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Sidebar_Category_Online {
            get {
                return ResourceManager.GetString("Sidebar_Category_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overig.
        /// </summary>
        internal static string Sidebar_Category_Other {
            get {
                return ResourceManager.GetString("Sidebar_Category_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kom gezellig praten!.
        /// </summary>
        internal static string Sidebar_Links_Discord {
            get {
                return ResourceManager.GetString("Sidebar_Links_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        internal static string Sidebar_Links_Github {
            get {
                return ResourceManager.GetString("Sidebar_Links_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steun ons.
        /// </summary>
        internal static string Sidebar_Links_Support {
            get {
                return ResourceManager.GetString("Sidebar_Links_Support", resourceCulture);
            }
        }
    }
}
