//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelWizard.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheelWizard.Resources.Languages.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Category_Video {
            get {
                return ResourceManager.GetString("Category_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string CompletePercentage {
            get {
                return ResourceManager.GetString("CompletePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting will force the game to run in 30 FPS (default is 60).
        /// </summary>
        public static string InfoText_30FPS {
            get {
                return ResourceManager.GetString("InfoText_30FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This enables the animations in the the Wheel Wizard app.
        /// </summary>
        public static string InfoText_EnableAnimations {
            get {
                return ResourceManager.GetString("InfoText_EnableAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must end with .exe.
        /// </summary>
        public static string InfoText_EndWithExe {
            get {
                return ResourceManager.GetString("InfoText_EndWithExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting disables Wiimote ingame, but enables it for the Wii channel.
        /// </summary>
        public static string InfoText_ForceDisableWiimote {
            get {
                return ResourceManager.GetString("InfoText_ForceDisableWiimote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will launch dolphins main window along with the game.
        /// </summary>
        public static string InfoText_LaunchWithDolphin {
            get {
                return ResourceManager.GetString("InfoText_LaunchWithDolphin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting will change certain dolphin settings to reduce stuttering and lag spikes.
        /// </summary>
        public static string InfoText_Recommended {
            get {
                return ResourceManager.GetString("InfoText_Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1x is the native resolution.
        /// </summary>
        public static string InfoText_ResolutionScale {
            get {
                return ResourceManager.GetString("InfoText_ResolutionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings are disabled, complete the location settings first.
        /// </summary>
        public static string InfoText_Topbar_LocationWarning {
            get {
                return ResourceManager.GetString("InfoText_Topbar_LocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin Emulator executable.
        /// </summary>
        public static string Option_DolphinEmulatorExe {
            get {
                return ResourceManager.GetString("Option_DolphinEmulatorExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin User Folder.
        /// </summary>
        public static string Option_DolphinUserPath {
            get {
                return ResourceManager.GetString("Option_DolphinUserPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Animations.
        /// </summary>
        public static string Option_EnableAnimations {
            get {
                return ResourceManager.GetString("Option_EnableAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Disable Wiimote.
        /// </summary>
        public static string Option_ForceDisableWiimote {
            get {
                return ResourceManager.GetString("Option_ForceDisableWiimote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Game With Dolphin Window.
        /// </summary>
        public static string Option_LaunchWithDolphin {
            get {
                return ResourceManager.GetString("Option_LaunchWithDolphin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Primary.
        /// </summary>
        public static string Option_MakePrimary {
            get {
                return ResourceManager.GetString("Option_MakePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario Kart Wii Game File.
        /// </summary>
        public static string Option_MarioKartGame {
            get {
                return ResourceManager.GetString("Option_MarioKartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Config Folder.
        /// </summary>
        public static string Option_OpenConfig {
            get {
                return ResourceManager.GetString("Option_OpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Settings.
        /// </summary>
        public static string Option_Recommended {
            get {
                return ResourceManager.GetString("Option_Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall RR.
        /// </summary>
        public static string Option_Reinstall {
            get {
                return ResourceManager.GetString("Option_Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Blur.
        /// </summary>
        public static string Option_RemoveBlur {
            get {
                return ResourceManager.GetString("Option_RemoveBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderer.
        /// </summary>
        public static string Option_Renderer {
            get {
                return ResourceManager.GetString("Option_Renderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro Rewind Language.
        /// </summary>
        public static string Option_RRLanguage {
            get {
                return ResourceManager.GetString("Option_RRLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show FPS.
        /// </summary>
        public static string Option_ShowFPS {
            get {
                return ResourceManager.GetString("Option_ShowFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSync.
        /// </summary>
        public static string Option_VSync {
            get {
                return ResourceManager.GetString("Option_VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel Wizard Language.
        /// </summary>
        public static string Option_WhWzLanguage {
            get {
                return ResourceManager.GetString("Option_WhWzLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Scale.
        /// </summary>
        public static string Option_WindowScale {
            get {
                return ResourceManager.GetString("Option_WindowScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Section_Installation {
            get {
                return ResourceManager.GetString("Section_Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Section_Language {
            get {
                return ResourceManager.GetString("Section_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Settings.
        /// </summary>
        public static string Section_LocationPaths {
            get {
                return ResourceManager.GetString("Section_LocationPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Settings.
        /// </summary>
        public static string Section_Performance {
            get {
                return ResourceManager.GetString("Section_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderer Settings.
        /// </summary>
        public static string Section_Renderer {
            get {
                return ResourceManager.GetString("Section_Renderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Section_Resolution {
            get {
                return ResourceManager.GetString("Section_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel Wizard appearance.
        /// </summary>
        public static string Section_WhWzAppearance {
            get {
                return ResourceManager.GetString("Section_WhWzAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii Settings.
        /// </summary>
        public static string Section_Wii {
            get {
                return ResourceManager.GetString("Section_Wii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Value_Language_Arabic {
            get {
                return ResourceManager.GetString("Value_Language_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Value_Language_ArabicOg {
            get {
                return ResourceManager.GetString("Value_Language_ArabicOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Value_Language_Chinese {
            get {
                return ResourceManager.GetString("Value_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Value_Language_ChineseOg {
            get {
                return ResourceManager.GetString("Value_Language_ChineseOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Value_Language_Czech {
            get {
                return ResourceManager.GetString("Value_Language_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Value_Language_CzechOg {
            get {
                return ResourceManager.GetString("Value_Language_CzechOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Value_Language_Dutch {
            get {
                return ResourceManager.GetString("Value_Language_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        public static string Value_Language_DutchOg {
            get {
                return ResourceManager.GetString("Value_Language_DutchOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Value_Language_English {
            get {
                return ResourceManager.GetString("Value_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Value_Language_EnglishOg {
            get {
                return ResourceManager.GetString("Value_Language_EnglishOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string Value_Language_Finnish {
            get {
                return ResourceManager.GetString("Value_Language_Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Value_Language_FinnishOg {
            get {
                return ResourceManager.GetString("Value_Language_FinnishOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Value_Language_France {
            get {
                return ResourceManager.GetString("Value_Language_France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string Value_Language_FranceOg {
            get {
                return ResourceManager.GetString("Value_Language_FranceOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Value_Language_German {
            get {
                return ResourceManager.GetString("Value_Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string Value_Language_GermanOg {
            get {
                return ResourceManager.GetString("Value_Language_GermanOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Value_Language_Italian {
            get {
                return ResourceManager.GetString("Value_Language_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        public static string Value_Language_ItalianOg {
            get {
                return ResourceManager.GetString("Value_Language_ItalianOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Value_Language_Japanese {
            get {
                return ResourceManager.GetString("Value_Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string Value_Language_JapaneseOg {
            get {
                return ResourceManager.GetString("Value_Language_JapaneseOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Value_Language_Korean {
            get {
                return ResourceManager.GetString("Value_Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        public static string Value_Language_KoreanOg {
            get {
                return ResourceManager.GetString("Value_Language_KoreanOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Value_Language_Norwegian {
            get {
                return ResourceManager.GetString("Value_Language_Norwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Value_Language_NorwegianOg {
            get {
                return ResourceManager.GetString("Value_Language_NorwegianOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Value_Language_Portuguese {
            get {
                return ResourceManager.GetString("Value_Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Value_Language_PortugueseOg {
            get {
                return ResourceManager.GetString("Value_Language_PortugueseOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Value_Language_Russian {
            get {
                return ResourceManager.GetString("Value_Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string Value_Language_RussianOg {
            get {
                return ResourceManager.GetString("Value_Language_RussianOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Value_Language_Spanish {
            get {
                return ResourceManager.GetString("Value_Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Value_Language_SpanishOg {
            get {
                return ResourceManager.GetString("Value_Language_SpanishOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Value_Language_Turkish {
            get {
                return ResourceManager.GetString("Value_Language_Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Value_Language_TurkishOg {
            get {
                return ResourceManager.GetString("Value_Language_TurkishOg", resourceCulture);
            }
        }
    }
}
